//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GuestBookEntities1 : DbContext
{
    public GuestBookEntities1()
        : base("name=GuestBookEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<cart> carts { get; set; }
    public virtual DbSet<cartItem> cartItems { get; set; }
    public virtual DbSet<guestbook> guestbooks { get; set; }
    public virtual DbSet<item> items { get; set; }
    public virtual DbSet<role> roles { get; set; }
    public virtual DbSet<user> users { get; set; }
}
