//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetWebForm.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int roleID { get; set; }
        public string roleName { get; set; }
        public string roleDesc { get; set; }
        public string groups { get; set; }
        public bool enabled { get; set; }
    }
}
